package formatter

const (
	Storage               int    = 1
	Telegram              int    = 2
	Internet              int    = 3
	constPhoto            int    = 0
	constAudio            int    = 1
	constVideo            int    = 2
	constDoc              int    = 3
	constAnim             int    = 4
	constVoice            int    = 5
	constVideoNote        int    = 6
	allowed               int    = 1
	interfaceKeyboard     string = "IKeyboard"
	interfaceParam        string = "IParameters"
	interfacePhoto        string = "IPhoto"
	interfaceVideo        string = "IVideo"
	interfaceAudio        string = "IAudio"
	interfaceDocument     string = "IDocument"
	interfaceInf          string = "MSG Information"
	interfaceChat         string = "IChat"
	interfaceAnimation    string = "IAnimation"
	interfaceVoice        string = "IVoice"
	interfaceInKB         string = "Inline Keyboard"
	interfaceReplyKB      string = "Reply Keyboard"
	interfaceForceReplyKB string = "ForceReply Keyobard"
	interfaceVideoNote    string = "IVideoNote"
	interfaceLocation     string = "ILocation"
	interfaceContact      string = "IConatact"
	interfacePoll         string = "IPoll"
	interfaceLink         string = "ILink"
	interfaceSticker      string = "ISticker"
	interfaceForum        string = "IForum"
	interfaceBot          string = "IBot"
	button                string = "Button"
	inbtn                 string = "Inline Button"
	rpbtn                 string = "Reply Button"
	interfaceInlineMode   string = "IInlineMode"
	checkString           int    = -1
	checkArray            int    = -2
	checkBool             int    = -3
	checkInt              int    = -4
	wURL                  int    = 0
	wCallback             int    = 1
	wWebApp               int    = 2
	wLoginUrl             int    = 3
	wSwitchIn             int    = 4
	wSwitchInQuery        int    = 5
	wSwitchInQueryCh      int    = 6
	wGame                 int    = 7
	wPay                  int    = 8
	wReqUsers             int    = 0
	wReqChat              int    = 1
	wReqContact           int    = 2
	wReqLocation          int    = 3
	wReqPoll              int    = 4
	wReqWebApp            int    = 5
	added                 int    = 1
)
